FORMAT: 1A
HOST: https://api.ngabarin.id/

# Ngabarin Consumer API

Dokumen ini digunakan untuk mengintegrasikan layanan ngabarin dengan website atau 
aplikasi anda menggunakan REST API. Untuk mendapatkan data secara real time, bisa
menggunakan koneksi websocket atau webhook.

Gunakan Ngabarin API Token pada setiap request.

# Format Respon:

Semua parameter dan key pada Request maupun Response menggunakan bahasa inggris dengan format snake case (huruf kecil yang dipisahkan dengan underscore).

Sukses 200
```
{
    "id":1,
    "username": "tegarimansyah"
}
```

Gagal 400, 401, 403, 404
```
{
    "result_code":1,
    "error_msg": "Registration Error",
    "error_desc": "Registration error, username or email already used",
    "error_info":  "http://docs.ngabarin.id/registration"
}
```

| HTTP Code | Status | Meaning |
|:---------:|--------------|:-----------------------------------------:|
| 200 | OK | Request execute successfully |
| 201 | Created | Request write on db successfully |
| 400 | Bad Request | Invalid format, check docs |
| 401 | Unauthorized | Use Authorization header or correct token |
| 403 | Forbidden | The path is not belong to you |
| 404 | Not Found | The path is not available |
