# Group Login dan Logout

## Login

### Login [POST /login]

### Refresh Token [POST /login/refresh]

## Logout

### Logout [POST /logout]

# Group Data Pengguna

## Mendapatkan Data Pengguna

### Mendapatkan Minimal Data [GET /user]

### Mendapatkan Data Tertentu [GET /user?extends=]

### Mendapatkan Semua Project Pengguna [GET /user?extends=projects]

### Mendapatkan Semua Data Pengguna [GET /user?extends=all]

## Update Data Pengguna

### Melakukan Update Data Pengguna [POST /user]

### Membuat Project Baru [PUT /user/new_projects]