# Group Data Pengguna

## Mendapatkan Data Pengguna [/user]

### Mendapatkan Minimal Data [GET /user]

+ Request (application/json)

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "tegarimansyah",
            "name": "Tegar Imansyah"
        }

### Mendapatkan Data Tertentu [GET /user{?extends}]

+ Request (application/json)

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + extends (optional) - List of extended information, separated by comma
        + Default: email,phone

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "tegarimansyah",
            "name": "Tegar Imansyah",
            "email": "tegar@ngabarin.id",
            "phone":"08123456789"
        }


### Mendapatkan Semua Data Pengguna [GET /user{?extends}]
Gunakan parameter `extends=all` untuk mendapat semua data

+ Request (application/json)

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + extends (optional) - List of extended information, separated by comma
        + Default: all

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "tegarimansyah",
            "name": "Tegar Imansyah",
            "email": "tegar@ngabarin.id",
            "phone":"08123456789",
            "address":"Sukolilo 19 Surabaya, Jawa Timur.",
            "projects": [
                { 
                  "name":"Hidroponik",
                  "slug": "hidroponik"
                },
                { 
                  "name":"Smart Home",
                  "slug": "smart-home"
                }
            ]
        }

### Update Data Pengguna [POST /user]

+ Request (application/json)
    Isi body yang mau di update sesuai dengan nama parameternya

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

    + Body

        {
            "phone":"0123456789"  
        }


+ Response 201 (application/json)

        {
            "response": "Data Updated"
        }


## Project Pengguna [/projects]


### Mendapatkan Semua Project Pengguna [GET /user/projects]

+ Request (application/json)

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "tegarimansyah",
            "projects": [
                { 
                  "name":"Hidroponik",
                  "slug": "hidroponik"
                },
                { 
                  "name":"Smart Home",
                  "slug": "smart-home"
                }
            ]
        }


### Membuat Project Baru [PUT /user/projects]

+ Request (application/json)
    Membuat project baru

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

    + Body

        {
            "Nama":"Surabaya Sanitasi"  
        }


+ Response 201 (application/json)

        {
            "response": "Project Created"
        }

