# Group Data Pengguna

## Mendapatkan Data Pengguna [/user]

### Mendapatkan Minimal Data [GET /user]

+ Request (application/json)

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "tegarimansyah",
            "name": "Tegar Imansyah"
        }

### Mendapatkan Data Tertentu [GET /user{?extends}]

+ Request (application/json)

    + Header

        NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

    + Parameters
        + extends (optional) - List of extended information, separated by comma
            + Default: "key, token"

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "tegarimansyah",
            "name": "Tegar Imansyah"
        }

### Mendapatkan Semua Project Pengguna [GET /user?extends=projects]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Semua Data Pengguna [GET /user?extends=all]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

## Update Data Pengguna [/userd]

### Melakukan Update Data Pengguna [POST /user]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Membuat Project Baru [PUT /user/new_projects]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

