# Group Data Pengguna

## Mendapatkan Data Pengguna [/user]

### Mendapatkan Minimal Data [GET /user]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Tertentu [GET /user?extends=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Semua Project Pengguna [GET /user?extends=projects]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Semua Data Pengguna [GET /user?extends=all]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

## Update Data Pengguna [/user]

### Melakukan Update Data Pengguna [POST /user]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Membuat Project Baru [PUT /user/new_projects]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

