# Group Data Project

## Mendapatkan Data Project

### Mendapatkan Minimal Data [GET /project/{nama_project}]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Tertentu [GET /project/{nama_project}?extends=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Semua Data Pengguna [GET /project/{nama_project}?extends=all]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

## Update Data Project

### Melakukan Update Data Project [POST /project/{nama_project}]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Membuat Project Baru [PUT /project/{nama_project}/new_data]

+ Response 200 (application/json)

        {
            "response": "OK"
        }