# Group Data Project

## Mendapatkan Data Project [/project]

### Mendapatkan Minimal Data [GET /project/{nama_project}]

+ Request (application/json)

    + Header

                NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project - Slug dari project. Slug dapat dilihat pada API `/user/projects`.


+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Nama Project",
            "username": "nama_project",
            "key": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg"
        }

### Mendapatkan Data Tertentu [GET /project/{nama_project}{?extends}]

+ Request (application/json)

    + Header

                NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + extends: address (optional) - List of extended information, separated by comma or comma URL encode `%2C`

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Nama Project",
            "username": "nama_project",
            "key": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg",
            "address": "Jl. Keputih, Surabaya Jawa Timur"
        }

### Mendapatkan Semua Data Project [GET /project/{nama_project}{?extends}]

+ Request (application/json)

    + Header

                NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + extends: address (optional) - List of extended information, separated by comma or comma URL encode `%2C`

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Nama Project",
            "username": "nama_project",
            "key": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg",
            "address": "Jl. Keputih, Surabaya Jawa Timur"
        }

### Melakukan Update Data Project [POST /project/{nama_project}]

+ Request (application/json)

    + Header

                NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

    + Body
            {
                "name":"Surabaya Project"
            }

+ Parameters
    + nama_project - Slug dari project. Slug dapat dilihat pada API `/user/projects`.

+ Response 201 (application/json)

        {
            "response": "Data Updated",
            "data": {
                "name":"Surabaya Project"
            }
        }

### Membuat Rekam Data Sensor Baru [PUT /project/{nama_project}/new_data]

+ Request (application/json)
    Membuat project baru

    + Header

                NGABARIN-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

    + Body

            {
                "gateway":"Sukolilo",
                "device":"sensor1",
                "loc":"-7.4564989,112.6766626",
                "data": [
                    {
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }

+ Response 201 (application/json)

        {
            "response": "Data Recorded",
            "new_record": {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        }

