# Group Data Project

## Mendapatkan Data Project

### Mendapatkan Minimal Data [GET /project/{nama_project}]

### Mendapatkan Data Tertentu [GET /project/{nama_project}?extends=]

### Mendapatkan Semua Data Pengguna [GET /project/{nama_project}?extends=all]

## Update Data Project

### Melakukan Update Data Project [POST /project/{nama_project}]

### Membuat Project Baru [PUT /project/{nama_project}/new_data]