# Group Data Sensor dan Aktuator

## Mendapatkan Data Sensor [/sensor]

### Mendapatkan Data Terbaru Semua Sensor [GET /project/{nama_project}/sensor]

+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project - Slug dari project. Slug dapat dilihat pada API `/user/projects`.


+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294005,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]


### Mendapatkan Data Dalam Range Waktu Semua Sensor [GET /project/{nama_project}/sensor{?from,until}]

+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + from: 1562007294000 - Unixtime data pertama yang diminta
    + until: 1562007294003 - Unixtime data terakhir yang diminta


+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

### Mendapatkan Data Terbaru Spesifik Sensor [GET /project/{nama_project}/sensor{?nama_sensor}]

+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + nama_sensor : Sensor+Panas,Sensor+PH - Spesifik sensor yang diminta. Multisensor dengan koma atau url encode nya dan spasi diganti dengan +


+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

### Mendapatkan Data Dalam Range Waktu Spesifik Sensor [GET /project/{nama_project}/sensor{?nama_sensor,from,until}]

+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + nama_sensor : Sensor+Panas,Sensor+PH - Spesifik sensor yang diminta. Multisensor dengan koma atau url encode nya dan spasi diganti dengan +
    + from: 1562007294000 - Unixtime data pertama yang diminta
    + until: 1562007294003 - Unixtime data terakhir yang diminta

+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

## Mengatur Data Aktuator [/aktuator]

### Mendapatkan Data Terbaru Semua Aktuator [GET /project/{nama_project}/actuator]


+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.

+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

### Mendapatkan Data Dalam Range Waktu Semua Aktuator [GET /project/{nama_project}/actuator{?from,until}]


+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + from: 1562007294000 - Unixtime data pertama yang diminta
    + until: 1562007294003 - Unixtime data terakhir yang diminta

+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

### Mendapatkan Data Terbaru Spesifik Aktuator [GET /project/{nama_project}/actuator{?nama_aktuator}]


+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + nama_sensor : Sensor+Panas,Sensor+PH - Spesifik sensor yang diminta. Multisensor dengan koma atau url encode nya dan spasi diganti dengan +

+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

### Mendapatkan Data Dalam Range Waktu Spesifik Aktuator [GET /project/{nama_project}/actuator{?nama_aktuator,from,until}]

+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.
    + nama_sensor : Sensor+Panas,Sensor+PH - Spesifik sensor yang diminta. Multisensor dengan koma atau url encode nya dan spasi diganti dengan +
    + from: 1562007294000 - Unixtime data pertama yang diminta
    + until: 1562007294003 - Unixtime data terakhir yang diminta

+ Response 200 (application/json)

        [
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294002,
                "data": [
                    {
                        "id":800,
                        "name":"Sensor Panas",
                        "value":"21"
                    },
                    {
                        "id":801,
                        "name":"Sensor PH",
                        "value":"5.7"
                    }
                ]
            },
            {
                "gateway":"Sukolilo",
                "gateway_id":3,
                "device":"sensor1",
                "device_id":2,
                "loc":"-7.4564989,112.6766626",
                "unixtime":1562007294000,
                "data": [
                    {
                        "id":744,
                        "name":"Sensor Panas",
                        "value":"20"
                    },
                    {
                        "id":745,
                        "name":"Sensor PH",
                        "value":"5.3"
                    }
                ]
            }
        ]

### Mengubah Data Spesifik Aktuator [PUT /project/{nama_project}/actuator]

+ Request (application/json)
    Mendapatkan 100 data terbaru dari semua sensor

    + Header

                Authorization : Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MzcyODQ3NTgsImlhdCI6MTUzNzE5ODMzOCwic3ViIjoxfQ.PgUyBkJhoOmTBny2aetjzpS-R2NS_H1E1KcC90iyaXg

    + Body

            {
                "gateway":"gateway_name",
                "device":"device_name",
                "data":"data"
            }

+ Parameters
    + nama_project : surabaya_hidroponik - Slug dari project. Slug dapat dilihat pada API `/user/projects`.

+ Response 200 (application/json)

        
        {
            "response": "Sent to device"
            "gateway":"Sukolilo",
            "gateway_id":3,
            "device":"sensor1",
            "device_id":2,
            "loc":"-7.4564989,112.6766626",
            "unixtime":1562007294002,
            "data": [
                {
                    "id":800,
                    "name":"Sensor Panas",
                    "value":"21"
                },
                {
                    "id":801,
                    "name":"Sensor PH",
                    "value":"5.7"
                }
            ]
        }

