# Group Data Sensor dan Aktuator

## Mendapatkan Data Sensor

### Mendapatkan Data Terbaru Semua Sensor [GET /project/{nama_project}/sensor]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Semua Sensor [GET /project/{nama_project}/sensor?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Terbaru Spesifik Sensor [GET /project/{nama_project}/sensor/{nama_sensor}]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Spesifik Sensor [GET /project/{nama_project}/sensor/{nama_sensor}?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

## Mengatur Data Aktuator

### Mendapatkan Data Terbaru Semua Aktuator [GET /project/{nama_project}/actuator]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Semua Aktuator [GET /project/{nama_project}/actuator?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Terbaru Spesifik Aktuator [GET /project/{nama_project}/actuator/{nama_aktuator}]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Spesifik Aktuator [GET /project/{nama_project}/actuator/{nama_aktuator}?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mengubah Data Spesifik Aktuator [PUT /project/{nama_project}/actuator]

+ Response 200 (application/json)

        {
            "response": "OK"
        }