FORMAT: 1A
HOST: https://api.ngabarin.id/

# Ngabarin Consumer API

Dokumen ini digunakan untuk mengintegrasikan layanan ngabarin dengan website atau 
aplikasi anda menggunakan REST API. Untuk mendapatkan data secara real time, bisa
menggunakan koneksi websocket atau webhook.

Gunakan Ngabarin API Token pada setiap request.

Format response:
Sukses 200
{
    "id":1,
    "username": "tegarimansyah"
}

Gagal 400, 401, 403, 404
```
{
    "result_code":1,
    "error_msg": "Registration Error",
    "error_desc": "Registration error, username or password already used",
    "error_info":  "http://docs.ngabarin.id/registration"
}
```

200 ok
201 created
400 bad request
401 unauthorized
403 forbidden
404 not found# Group Konektivitas Cloud

## PING  [/ping]

### PING [GET /ping]
+ Requests 

    + Headers
    
            NGABARIN-TOKEN: NGABARIN-USER-TOKEN
            
+ Response 200 (application/json)

        {
            "response": "OK"
        }
        
+ Response 403 (application/json)

        {
            "result_code":1,
            "error_msg": "Unauthorized",
            "error_desc": "Unauthorized data request",
            "error_info":  "https://ngabarin.docs.apiary.io/#reference/login-dan-logout"
        }
        
# Group Login dan Logout

## Login

### Login [POST /login]

### Refresh Token [POST /login/refresh]

## Logout

### Logout [POST /logout]

# Group Data Pengguna

## Mendapatkan Data Pengguna

### Mendapatkan Minimal Data [GET /user]

### Mendapatkan Data Tertentu [GET /user?extends=]

### Mendapatkan Semua Project Pengguna [GET /user?extends=projects]

### Mendapatkan Semua Data Pengguna [GET /user?extends=all]

## Update Data Pengguna

### Melakukan Update Data Pengguna [POST /user]

### Membuat Project Baru [PUT /user/new_projects]# Group Data Pengguna

## Mendapatkan Data Pengguna

### Mendapatkan Minimal Data [GET /user]

### Mendapatkan Data Tertentu [GET /user?extends=]

### Mendapatkan Semua Project Pengguna [GET /user?extends=projects]

### Mendapatkan Semua Data Pengguna [GET /user?extends=all]

## Update Data Pengguna

### Melakukan Update Data Pengguna [POST /user]

### Membuat Project Baru [PUT /user/new_projects]# Group Data Project

## Mendapatkan Data Project

### Mendapatkan Minimal Data [GET /project/{nama_project}]

### Mendapatkan Data Tertentu [GET /project/{nama_project}?extends=]

### Mendapatkan Semua Data Pengguna [GET /project/{nama_project}?extends=all]

## Update Data Project

### Melakukan Update Data Project [POST /project/{nama_project}]

### Membuat Project Baru [PUT /project/{nama_project}/new_data]# Group Data Sensor dan Aktuator

## Mendapatkan Data Sensor

### Mendapatkan Data Terbaru Semua Sensor [GET /project/{nama_project}/sensor]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Semua Sensor [GET /project/{nama_project}/sensor?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Terbaru Spesifik Sensor [GET /project/{nama_project}/sensor/{nama_sensor}]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Spesifik Sensor [GET /project/{nama_project}/sensor/{nama_sensor}?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

## Mengatur Data Aktuator

### Mendapatkan Data Terbaru Semua Aktuator [GET /project/{nama_project}/actuator]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Semua Aktuator [GET /project/{nama_project}/actuator?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Terbaru Spesifik Aktuator [GET /project/{nama_project}/actuator/{nama_aktuator}]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mendapatkan Data Dalam Range Waktu Spesifik Aktuator [GET /project/{nama_project}/actuator/{nama_aktuator}?from=&until=]

+ Response 200 (application/json)

        {
            "response": "OK"
        }

### Mengubah Data Spesifik Aktuator [PUT /project/{nama_project}/actuator]

+ Response 200 (application/json)

        {
            "response": "OK"
        }